name: cached_network_image_platform_interface
description: Platform interface for CachedNetworkImage
version: 4.1.1
homepage: https://github.com/arham-anees/flutter_cached_network_image_2

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ">=4.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
